/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdmin;

import Business.EcoSystem;
import Business.Handler.DataHandler;
import Business.Model.Club;
import Business.Model.Director;
import Business.Network.League;
import Business.Organization.Organization;
import Business.Role.LeagueDirectorRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author akash
 */
public class SuperAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SuperAdminWorkAreaJPanel
     */
    private EcoSystem system;
    private JPanel userProcessContainer;
    private DataHandler ch;
    private CardLayout cl;
    private League selectedLeague;
    
    public SuperAdminWorkAreaJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.system = system;
        this.userProcessContainer = userProcessContainer;
    }

    public SuperAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business) {
       initComponents();
       this.createPanel.setVisible(false);
       this.system = business;
       cl = (CardLayout) this.getLayout();
       ch = new DataHandler();
        if(this.system.getleaguesList().isEmpty()){
            this.system.setleaguesList(ch.getChampionsLeague());
        }
        this.userProcessContainer = userProcessContainer;
        populateTable();
        populateTree();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChampionsLeaguePanel = new javax.swing.JPanel();
        createLeague = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        ManageLeague = new javax.swing.JPanel();
        createPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        leagueNameText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        leagueNameAdminText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        leagueAdminUsernameText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        leagueAdminPassword = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        leagueAdminConfirmPassword = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        createLeagueAdmin = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        ChampionsLeaguePanel.setBackground(new java.awt.Color(51, 51, 51));

        createLeague.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        createLeague.setForeground(new java.awt.Color(0, 0, 51));
        createLeague.setText("Manage Leagues");
        createLeague.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createLeagueActionPerformed(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.setRootVisible(false);
        jScrollPane1.setViewportView(jTree1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout ChampionsLeaguePanelLayout = new javax.swing.GroupLayout(ChampionsLeaguePanel);
        ChampionsLeaguePanel.setLayout(ChampionsLeaguePanelLayout);
        ChampionsLeaguePanelLayout.setHorizontalGroup(
            ChampionsLeaguePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChampionsLeaguePanelLayout.createSequentialGroup()
                .addGroup(ChampionsLeaguePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ChampionsLeaguePanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ChampionsLeaguePanelLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(createLeague, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(139, 139, 139)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        ChampionsLeaguePanelLayout.setVerticalGroup(
            ChampionsLeaguePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChampionsLeaguePanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(createLeague, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
        );

        add(ChampionsLeaguePanel, "card2");

        ManageLeague.setBackground(new java.awt.Color(51, 51, 51));

        createPanel.setBackground(new java.awt.Color(102, 102, 102));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel6.setText("Create League Admin");

        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setText("League Name :");

        jLabel2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel2.setText("League admin name :");

        jLabel3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel3.setText("League admin username :");

        jLabel4.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel4.setText("League admin password :");

        jLabel5.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel5.setText("League admin confirm password :");

        jButton2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 51));
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createPanelLayout = new javax.swing.GroupLayout(createPanel);
        createPanel.setLayout(createPanelLayout);
        createPanelLayout.setHorizontalGroup(
            createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createPanelLayout.createSequentialGroup()
                        .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createPanelLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(leagueAdminUsernameText)
                                    .addComponent(leagueAdminPassword)
                                    .addComponent(leagueNameAdminText)
                                    .addComponent(leagueNameText)))
                            .addGroup(createPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(leagueAdminConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(82, 82, 82))))
            .addGroup(createPanelLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        createPanelLayout.setVerticalGroup(
            createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(createPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(createPanelLayout.createSequentialGroup()
                        .addComponent(leagueNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(leagueNameAdminText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leagueAdminUsernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(leagueAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(leagueAdminConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jButton2)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "League name", "League Admin name"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        createLeagueAdmin.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        createLeagueAdmin.setText("Create League admin");
        createLeagueAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createLeagueAdminActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jButton3.setText("Add League");

        javax.swing.GroupLayout ManageLeagueLayout = new javax.swing.GroupLayout(ManageLeague);
        ManageLeague.setLayout(ManageLeagueLayout);
        ManageLeagueLayout.setHorizontalGroup(
            ManageLeagueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageLeagueLayout.createSequentialGroup()
                .addGroup(ManageLeagueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManageLeagueLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jButton1)
                        .addGap(45, 45, 45)
                        .addComponent(jButton3)
                        .addGap(53, 53, 53)
                        .addComponent(createLeagueAdmin))
                    .addGroup(ManageLeagueLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(createPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ManageLeagueLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(363, Short.MAX_VALUE))
        );
        ManageLeagueLayout.setVerticalGroup(
            ManageLeagueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageLeagueLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ManageLeagueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createLeagueAdmin)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(createPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        add(ManageLeague, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void createLeagueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createLeagueActionPerformed
        cl.show(this, "card3");
    }//GEN-LAST:event_createLeagueActionPerformed

    private void createLeagueAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createLeagueAdminActionPerformed
    int selectedRow = jTable1.getSelectedRow();
        if(selectedRow>= 0){
            this.createPanel.setVisible(true);
            this.selectedLeague = (League)jTable1.getValueAt(selectedRow, 0);
            leagueNameText.setText(this.selectedLeague.getLeague().getName());
        }else JOptionPane.showMessageDialog(null, "Please select a League!");
    }//GEN-LAST:event_createLeagueAdminActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       cl.previous(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    String leagueName = leagueNameText.getText();
    String leagueAdminName = leagueNameAdminText.getText();
    String userName = leagueAdminUsernameText.getText();
    String password = leagueAdminPassword.getText();
    Director l = new Director(leagueAdminName,this.selectedLeague);
    this.selectedLeague.setLeagueAdmin(l);
    system.getUserAccountDirectory().createUserAccount(userName, password, new LeagueDirectorRole(),l);
    JOptionPane.showMessageDialog(this,"League Admin Created Succesfully!");
    leagueNameAdminText.setText("");
    leagueAdminUsernameText.setText("");
    leagueAdminPassword.setText("");
    this.createPanel.setVisible(false);
    populateTable();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        for(League l : system.getleaguesList()){
        Object[] row = new Object[2];
                row[0] = l;
                if(l.getLeagueAdmin() == null){
                    row[1] = "Admin Not Created";
                }
                else row[1] = l.getLeagueAdmin();
                dtm.addRow(row);
        }
    }

     public void populateTree(){
        DefaultMutableTreeNode leagueNode;
        DefaultMutableTreeNode clubNode;
        League league;
        Club club;
        DefaultTreeModel model=(DefaultTreeModel)jTree1.getModel();
        DefaultMutableTreeNode leagues=new DefaultMutableTreeNode(this.system.getChampionsLeague());
        DefaultMutableTreeNode root=(DefaultMutableTreeNode)model.getRoot();
        root.removeAllChildren();
        model.setRoot(root);
        root.insert(leagues, 0);
        for(int i = 0;i<this.system.getleaguesList().size();i++){
            league=this.system.getleaguesList().get(i);
            leagueNode=new DefaultMutableTreeNode(league.getLeague().getName());
            leagues.insert(leagueNode, i);
            ArrayList<Club> topClubs = ch.getTopFourTeams(ch.getStandings(league.getLeague().getId()));
            for(int j= 0; j<topClubs.size();j++){
                club = topClubs.get(j);
                clubNode = new DefaultMutableTreeNode(club.getName());
                leagueNode.insert(clubNode,j);
            }
        }
         model.reload();
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChampionsLeaguePanel;
    private javax.swing.JPanel ManageLeague;
    private javax.swing.JButton createLeague;
    private javax.swing.JButton createLeagueAdmin;
    private javax.swing.JPanel createPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTree jTree1;
    private javax.swing.JTextField leagueAdminConfirmPassword;
    private javax.swing.JTextField leagueAdminPassword;
    private javax.swing.JTextField leagueAdminUsernameText;
    private javax.swing.JTextField leagueNameAdminText;
    private javax.swing.JTextField leagueNameText;
    // End of variables declaration//GEN-END:variables
}
