/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdmin;

import Business.EcoSystem;
import Business.Handler.DataHandler;
import Business.Model.Club;
import Business.Model.Competition;
import Business.Network.League;
import Business.Organization.Organization;
import Business.Role.LeagueDirectorRole;
import Business.UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author akash
 */
public class SuperAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SuperAdminWorkAreaJPanel
     */
    private EcoSystem system;
    private JPanel userProcessContainer;
    private DataHandler ch;
    
    public SuperAdminWorkAreaJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.system = system;
        this.userProcessContainer = userProcessContainer;
    }

    public SuperAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business) {
       initComponents();
       this.system = business;
       ch = new DataHandler();
        if(this.system.getleaguesList().isEmpty()){
            this.system.setleaguesList(ch.getChampionsLeague());
        }
        this.userProcessContainer = userProcessContainer;
        populateTable();
        populateTree();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createLeague = new javax.swing.JButton();
        removeLeague = new javax.swing.JButton();
        viewLeague = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        leagueNameText = new javax.swing.JTextField();
        leagueNameAdminText = new javax.swing.JTextField();
        leagueAdminUsernameText = new javax.swing.JTextField();
        leagueAdminPassword = new javax.swing.JTextField();
        leagueAdminConfirmPassword = new javax.swing.JTextField();
        submitLeague = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        createLeague.setText("Create league");

        removeLeague.setText("Remove League");

        viewLeague.setText("View League Details");

        jLabel1.setText("League Name :");

        jLabel2.setText("League admin name :");

        jLabel3.setText("League admin username :");

        jLabel4.setText("League admin password :");

        jLabel5.setText("League admin confirm password :");

        submitLeague.setText("Submit");
        submitLeague.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitLeagueActionPerformed(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(viewLeague)
                                .addGap(62, 62, 62)
                                .addComponent(removeLeague)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(createLeague))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(leagueAdminConfirmPassword))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(leagueAdminPassword))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(leagueAdminUsernameText))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(leagueNameAdminText))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(leagueNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(submitLeague)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createLeague)
                    .addComponent(removeLeague)
                    .addComponent(viewLeague))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(leagueNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(leagueNameAdminText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(leagueAdminUsernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(leagueAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(leagueAdminConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submitLeague)
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitLeagueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitLeagueActionPerformed
    String leagueName = leagueNameText.getText();
    String leagueAdminName = leagueNameAdminText.getText();
    String userName = leagueAdminUsernameText.getText();
    String password = leagueAdminPassword.getText();
    League l = new League(leagueName, leagueAdminName);
    system.getUserAccountDirectory().createUserAccount(userName, password, new LeagueDirectorRole(),l.getLeagueAdmin());
        JOptionPane.showMessageDialog(this,"");
    }//GEN-LAST:event_submitLeagueActionPerformed

    public void populateTable(){
    //    DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
    //    dtm.setRowCount(0);
    //    for(Competition l : system.getleaguesList()){
    //    Object[] row = new Object[2];
    //            row[0] = l;
    //            row[1] = l;
    //            dtm.addRow(row);
    //    }
    }

     public void populateTree(){
        DefaultMutableTreeNode leagueNode;
        DefaultMutableTreeNode clubNode;
        Competition league;
        Club club;
        DefaultTreeModel model=(DefaultTreeModel)jTree1.getModel();
        DefaultMutableTreeNode leagues=new DefaultMutableTreeNode(this.system.getChampionsLeague());
        DefaultMutableTreeNode root=(DefaultMutableTreeNode)model.getRoot();
        root.removeAllChildren();
        model.setRoot(root);
        root.insert(leagues, 0);
        for(int i = 0;i<this.system.getleaguesList().size();i++){
            league=this.system.getleaguesList().get(i);
            leagueNode=new DefaultMutableTreeNode(league.getName());
            leagues.insert(leagueNode, i);
            ArrayList<Club> topClubs = ch.getTopFourTeams(ch.getStandings(league.getId()));
            for(int j= 0; j<topClubs.size();j++){
                club = topClubs.get(j);
                clubNode = new DefaultMutableTreeNode(club.getName());
                leagueNode.insert(clubNode,j);
            }
        }
         model.reload();
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createLeague;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JTextField leagueAdminConfirmPassword;
    private javax.swing.JTextField leagueAdminPassword;
    private javax.swing.JTextField leagueAdminUsernameText;
    private javax.swing.JTextField leagueNameAdminText;
    private javax.swing.JTextField leagueNameText;
    private javax.swing.JButton removeLeague;
    private javax.swing.JButton submitLeague;
    private javax.swing.JButton viewLeague;
    // End of variables declaration//GEN-END:variables
}
